### ISSUE TITLE
Dates mismatching 

### ISSUE THREAD

**Issue by azmatullah** [rezaies/moodle-calendartype_hijri#1]
We're facing some dates mismatching issue while using HIJRI calendar even we used algorithm either A or B, below are some details.

Lets use Month `Rajab` in our example.

Total no. of days in UmmulQura : 29 
Total no. of days if we used algorithm A: 30 days
Total no. of days if we used algorithm B: 30 days

Due to no. of days difference its impact on some dates as well.

1st Rajab as per UmmulQura is : Friday 8/3/2019
1st Rajab as per Algorithm A is : Friday 8/3/2019 (1 Day extra in last of Month)
1st  Rajab as per Algorithm B is: Thursday 7/3/2019(1 Day extra in last of Month)

Can you consider to add UmmulQura as a new Algorithm?
The official website of UmmulaQura calender :  http://www.ummulqura.org.sa/

Note: Android also using UmmulaQura Algoritham in [core calendar](https://developer.android.com/reference/android/icu/util/IslamicCalendar)

**Comment by rezaies** [comment]
Thank you, Azmatullah, for reporting this issue.
According to [Wikipedia](https://en.wikipedia.org/wiki/Rajab), "Some believe that the month is 29 days and others believe that the month is 30 days."
Apparently, I need to add a new algorithm (Algorithm C).
Are you able to point me to a conversion code (in any programming language) that is working for you?

**Comment by rezaies** [comment]
https://github.com/top7up/Hijri seems to be helpful. Posting here so I can look later.

**Comment by azmatksa** [comment]
Hi @rezaies is there any updates regarding the calendar? 

(When we select hijri calendar and comes to tha calendar page it showing "Invalid parameter" error,)

**Comment by rezaies** [comment]
Thank you @azmatksa for reaching out.
I am not aware of the issue you reported.
Can you please create a new issue here and provide as much details to replicate the issue you are having? Like which conversion algorithm you are using, and what is your Moodle version?

**Comment by rezaies** [comment]
Umm al-Qura conversion algorithm is added in the new version.
