### ISSUE TITLE
Missing required key in single structure: year

### ISSUE THREAD

**Issue by omerrkhalidd** [rezaies/moodle-calendartype_hijri#2]
Hello 
i installed the hijri calendar with moodle 3.10 and the default boost theme and am getting this error 

Missing required key in single structure: year
Error code: invalidparameter
* line 349 of /lib/externallib.php: invalid_parameter_exception thrown
* line 240 of /lib/externallib.php: call to external_api::validate_parameters()
* line 81 of /lib/ajax/service.php: call to external_api::call_external_function()

![Screenshot_2021-01-09 Dashboard](https://user-images.githubusercontent.com/20067872/104090963-f2f06900-5282-11eb-818f-c72847fe7ff4.png)

**Comment by rezaies** [comment]
Thank you for reporting this issue.
I have put this in the backlog.

**Comment by rezaies** [comment]
After further investigation, it turned out that the issue you are experiencing is because of a bug in the Moodle core. I have provided a fix for that at https://tracker.moodle.org/browse/MDL-70625. Hopefully, it will be integrated soon.

**Comment by azmatksa** [comment]
@rezaies  I try to merge these changes but I still getting same error on 3.9, I'm using custom calendar plugin based on hijri calendar!

**Comment by rezaies** [comment]
Hi @azmatksa 
I don't know about your custom calendar plugin, but the new version of this plugin works well if the core bug I mentioned above is fixed, and it supports the Umm al-Qura calendar as well.
